### ISSUE TITLE
Youtube stream Error

### ISSUE THREAD

**Issue by worgil** [aau-zid/BigBlueButton-liveStreaming#104]
Hi all,
when we try stream with you tube looking error below. bad sound and freeze, disconnecting YouTube live stream.

`YouTube is not receiving enough video to maintain smooth streaming. As such, viewers will experience buffering.
`
my yml file below. thanks.
```
version: '3.3'
services:
  bbb-streamer:
    image: aauzid/bigbluebutton-livestreaming
    container_name: liveStreaming
    shm_size: '2gb'
    environment:
      # BigBlueButton Server url:
      - BBB_URL=https://bmocevrimici.org/bigbluebutton/api
      # BigBlueButton secret:
      - BBB_SECRET=mysecret
      # BigBlueButton meetingID:
      - BBB_MEETING_ID=myid
      # start meeting (optional):
      - BBB_START_MEETING=true
      # attendee password (optional - has to be set to the attendee password of moodle/greenlight or any other frontend to allow joining via their links):
      - BBB_ATTENDEE_PASSWORD=secret
      # moderator password (optional - has to be set to the moderator password of moodle/greenlight or any other frontend to allow joining via their links):
      - BBB_MODERATOR_PASSWORD=secret
      # meeting title (optional):
      - BBB_MEETING_TITLE=BMO Live
      # Media server url:
      - BBB_STREAM_URL=rtmp://a.rtmp.youtube.com/live2/mylink

      - BBB_RESOLUTION=1920x1080
      # stream video bitrate
      - FFMPEG_STREAM_VIDEO_BITRATE=3000
      # threads used for stream (0=auto)
      - FFMPEG_STREAM_THREADS=0
      # Timezone (default: Europe/Vienna):
      - TZ=Europe/Vienna
    volumes:
      - ./videodata:/video
```
