### ISSUE TITLE
Fail on chat_send.click()

### ISSUE THREAD

**Issue by moan0s** [aau-zid/BigBlueButton-liveStreaming#124]
**Describe the bug**
The streamer fails during start. It seems to be an issue with `chat_send.click()`

**To Reproduce**
Pull newest docker image, configure, try to start with `docker-compose up`

**Expected behavior**
I would expect a user to join a meeting (which happens for a second, this user is called "Live") and the stream to begin (which does not happen). Also the container creashes.  Here is the log
```

root@XXXXXX:~# docker-compose up 
Starting liveStreaming ... done
Attaching to liveStreaming
liveStreaming   | Skipping nsswrapper setup - already initialized
liveStreaming   | Starting pulseaudio...
liveStreaming   | Waiting for pulseaudio to start...
liveStreaming   | Skipping nsswrapper setup - already initialized
liveStreaming   | INFO:root:Starting browser!!
liveStreaming   | INFO:root:streaming intro...
liveStreaming   | ffmpeg version 4.3.2-0york0~18.04 Copyright (c) 2000-2021 the FFmpeg developers
liveStreaming   |   built with gcc 7 (Ubuntu 7.5.0-3ubuntu1~18.04)
liveStreaming   |   configuration: --prefix=/usr --extra-version='0york0~18.04' --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-libzimg --enable-pocketsphinx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
liveStreaming   |   libavutil      56. 51.100 / 56. 51.100
liveStreaming   |   libavcodec     58. 91.100 / 58. 91.100
liveStreaming   |   libavformat    58. 45.100 / 58. 45.100
liveStreaming   |   libavdevice    58. 10.100 / 58. 10.100
liveStreaming   |   libavfilter     7. 85.100 /  7. 85.100
liveStreaming   |   libavresample   4.  0.  0 /  4.  0.  0
liveStreaming   |   libswscale      5.  7.100 /  5.  7.100
liveStreaming   |   libswresample   3.  7.100 /  3.  7.100
liveStreaming   |   libpostproc    55.  7.100 / 55.  7.100
liveStreaming   | false: No such file or directory
liveStreaming   | INFO:root:Open BBB and hide elements!!
liveStreaming   | INFO:root:get_join_url...
liveStreaming   | INFO:root:https://bbb.hyteck.de/bigbluebutton/api/join?meetingID=89dc77555f0a37c6c61bb02b7dd1c0105c47cc84&fullName=Live&password=ooBdOwdKYjsZ&userdata-bbb_auto_join_audio=true&userdata-bbb_enable_video=true&userdata-bbb_listen_only_mode=true&userdata-bbb_force_listen_only=true&userdata-bbb_skip_check_audio=true&joinViaHtml5=true&checksum=XXXXXXXXXXXXXXXXXXXX
liveStreaming   | INFO:root:Waiting for chat input window to appear.
liveStreaming   | Traceback (most recent call last):
liveStreaming   |   File "stream.py", line 255, in <module>
liveStreaming   |     bbb_browser()
liveStreaming   |   File "stream.py", line 156, in bbb_browser
liveStreaming   |     chat_send.click()
liveStreaming   |   File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webelement.py", line 80, in click
liveStreaming   |     self._execute(Command.CLICK_ELEMENT)
liveStreaming   |   File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
liveStreaming   |     return self._parent.execute(command, params)
liveStreaming   |   File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
liveStreaming   |     self.error_handler.check_response(response)
liveStreaming   |   File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
liveStreaming   |     raise exception_class(message, screen, stacktrace)
liveStreaming   | selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <button aria-label="Send message" aria-disabled="false" class="md--Q7ug4 buttonWrapper--x8uow sendButton--Z93EzE" type="submit" position="bottom" id="tippy-51">...</button> is not clickable at point (500, 1025). Other element would receive the click: <div class="ReactModal__Overlay ReactModal__Overlay--after-open overlay--Z7FUVK">...</div>
liveStreaming   |   (Session info: chrome=89.0.4389.114)
liveStreaming   | 
liveStreaming exited with code 1

```
When I use the join link to join the meeting manually, this works as I would expect it (I am a live user that can hear).

I happily provide more information.

**Comment by mtsonline** [comment]
hi and thanks for the report.
what bbb version are you using?
Did you change any settings in your bbb?
have you chat enabled in liveStreaming?
...
cheers

**Comment by moan0s** [comment]
TBH I don't know how to enable chat in liveStreaming, I only changed the `docker-compose.yml`

```
 root@XXXXX:~/stream# cat docker-compose.yml 
version: '3.3'
services:
  bbb-streamer:
    image: aauzid/bigbluebutton-livestreaming
    container_name: liveStreaming
    shm_size: '2gb'
    environment:
      # BigBlueButton Server url:
      - BBB_URL=https://bbb.hyteck.de/bigbluebutton/api
      # BigBlueButton secret:
      - BBB_SECRET=XXXXXXXXXXXXXXXXXXXXXXXX
      # BigBlueButton meetingID:
      - BBB_MEETING_ID=XXXXXXXXXXXXXXXXXXx
      # start meeting (optional):
      - BBB_START_MEETING=false
      # attendee password (optional - has to be set to the attendee password of moodle/greenlight or any other frontend to allow joining via their links):
      #- BBB_ATTENDEE_PASSWORD=IVLHwOBSVmYP
      # moderator password (optional - has to be set to the moderator password of moodle/greenlight or any other frontend to allow joining via their links):
      #- BBB_MODERATOR_PASSWORD=JjeQYksarqLQ
      # meeting title (optional):
      - BBB_MEETING_TITLE=XXXXXXXXXXX
      # download / save BigBlueButton meeting
      - BBB_DOWNLOAD_MEETING=false
      # play intro file (can be a local file in videodata folder e.g. /video/intro.mp4 or a url of a mediastream e.g. https://my.intro.stream)
      - BBB_INTRO=false
      # begin the intro at position (optional, e.g. 00:00:05)
      #- BBB_BEGIN_INTRO_AT=04:40
      # end intro after (optional, e.g. 01:00:00 - after one hour)
      #- BBB_END_INTRO_AT=
      # Media server url:
      - BBB_STREAM_URL=rtmp://stream.hyteck.de/live/XXXXXXXXXXXXXXXXX/
      # Resolution to be streamed/downloaded in format WxH (default 1920x1080)
      - BBB_RESOLUTION=1920x1080
      # stream video bitrate
      - FFMPEG_STREAM_VIDEO_BITRATE=4000
      # threads used for stream (0=auto)
      - FFMPEG_STREAM_THREADS=0
      # Timezone (default: Europe/Vienna):
      - TZ=Europe/Berlin

    volumes:
      - ./videodata:/video

```


I changed the following (moitoring and minor things)
```
enableHTML5ClientLog
setHTML5ClientAsDefault
enableUFWRules


echo "  Add monitoring to nginx"
  cat <<HERE > /etc/bigbluebutton/nginx/monitoring.nginx
# BigBlueButton Exporter (metrics)
location /metrics/ {
    auth_basic "BigBlueButton Exporter";
    auth_basic_user_file /etc/nginx/.htpasswd;
    proxy_pass http://127.0.0.1:9688/;
    include proxy_params;
}
```


This is the full version information

```
root@XXXXX:~/stream# bbb-conf --version

ii  bbb-apps                              1:2.2.0-51                                      amd64        BigBlueButton applications for Red5
ii  bbb-apps-akka                         2.2.0-97                                        all          BigBlueButton Apps (Akka)
ii  bbb-apps-screenshare                  1:2.2.0-51                                      amd64        BigBlueButton screenshare module for Red5
ii  bbb-apps-sip                          1:2.2.0-11                                      amd64        BigBlueButton SIP module for Red5
ii  bbb-apps-video                        1:2.2.0-49                                      amd64        BigBlueButton video module for Red5
ii  bbb-apps-video-broadcast              1:2.2.0-8                                       amd64        BigBlueButton video broadcast module for Red5
ii  bbb-client                            1:2.2.0-40                                      amd64        BigBlueButton Flash client
ii  bbb-config                            1:2.2.0-234                                     amd64        BigBlueButton configuration utilities
ii  bbb-etherpad                          1:2.2.0-66                                      amd64        The EtherPad Lite components for BigBlueButton
ii  bbb-freeswitch-core                   2:2.2.0-113                                     amd64        BigBlueButton build of FreeSWITCH
ii  bbb-freeswitch-sounds                 1:1.6.7-6                                       amd64        FreeSWITCH Sounds
ii  bbb-fsesl-akka                        2.2.0-73                                        all          BigBlueButton FS-ESL (Akka)
ii  bbb-html5                             1:2.2.0-1114                                    amd64        The HTML5 components for BigBlueButton
ii  bbb-mkclean                           1:0.8.7-3                                       amd64        Clean and optimize Matroska and WebM files
ii  bbb-playback-presentation             1:2.2.0-35                                      amd64        BigBluebutton playback of presentation
ii  bbb-record-core                       1:2.2.0-72                                      amd64        BigBlueButton record and playback
ii  bbb-red5                              1:1.0.10-16                                     amd64        The Red5 server for BigBlueButton
ii  bbb-transcode-akka                    2.2.0-8                                         all          BigBlueButton Transcoder
ii  bbb-web                               1:2.2.0-150                                     amd64        BigBlueButton API
ii  bbb-webrtc-sfu                        1:2.2.0-110                                     amd64        BigBlueButton WebRTC SFU
ii  bigbluebutton                         1:2.2.0-5                                       amd64        Open source web conferencing platform (bbb)
ii  ffmpeg                                7:4.2.4-1ubuntu0.1bbb1~16.04.1                  amd64        Tools for transcoding, streaming and playing of multimedia files
ii  libavcodec58:amd64                    7:4.2.4-1ubuntu0.1bbb1~16.04.1                  amd64        FFmpeg library with de/encoders for audio/video codecs - runtime files
ii  libavdevice58:amd64                   7:4.2.4-1ubuntu0.1bbb1~16.04.1                  amd64        FFmpeg library for handling input and output devices - runtime files
ii  libavfilter7:amd64                    7:4.2.4-1ubuntu0.1bbb1~16.04.1                  amd64        FFmpeg library containing media filters - runtime files
ii  libavformat58:amd64                   7:4.2.4-1ubuntu0.1bbb1~16.04.1                  amd64        FFmpeg library with (de)muxers for multimedia containers - runtime files
ii  libavresample4:amd64                  7:4.2.4-1ubuntu0.1bbb1~16.04.1                  amd64        FFmpeg compatibility library for resampling - runtime files
ii  libavutil56:amd64                     7:4.2.4-1ubuntu0.1bbb1~16.04.1                  amd64        FFmpeg library with functions for simplifying programming - runtime files
ii  libopusenc0                           0.2.1-1bbb1                                     amd64        High-level API for encoding Ogg Opus audio streams
ii  libpostproc55:amd64                   7:4.2.4-1ubuntu0.1bbb1~16.04.1                  amd64        FFmpeg library for post processing - runtime files
ii  libswresample3:amd64                  7:4.2.4-1ubuntu0.1bbb1~16.04.1                  amd64        FFmpeg library for audio resampling, rematrixing etc. - runtime files
ii  libswscale5:amd64                     7:4.2.4-1ubuntu0.1bbb1~16.04.1                  amd64        FFmpeg library for image scaling and various conversions - runtime files

```
