### ISSUE TITLE
Waiting for chat window to appear error

### ISSUE THREAD

**Issue by Amanb1145** [aau-zid/BigBlueButton-liveStreaming#141]
I am trying to stream on youtube but the Live user leaves after sometime.

```
version: '3.3'
services:
  bbb-streamer:
    image: aauzid/bigbluebutton-livestreaming
    container_name: liveStreaming
    shm_size: '2gb'
    environment:
      # BigBlueButton Server url:
      - BBB_URL=https://some_url/bigbluebutton/api/
      # BigBlueButton secret:
      - BBB_SECRET=secret
      # BigBlueButton meetingID:
      - BBB_MEETING_ID=d34eec2b-904e-441d-8ff5-3c73af4b0d8a
      # start meeting (optional):
      - BBB_START_MEETING=false
      # attendee password (optional - has to be set to the attendee password of moodle/greenlight or any other frontend to allow joining via their links):
      - BBB_ATTENDEE_PASSWORD=
      # moderator password (optional - has to be set to the moderator password of moodle/greenlight or any other frontend to allow joining via their links):
      - BBB_MODERATOR_PASSWORD=
      # meeting title (optional):
      - BBB_MEETING_TITLE=liveStreaming Test
      # download / save BigBlueButton meeting
      - BBB_DOWNLOAD_MEETING=
      # play intro file (can be a local file in videodata folder e.g. /video/intro.mp4 or a url of a mediastream e.g. https://my.intro.stream)
      - BBB_INTRO=
      # begin the intro at position (optional, e.g. 00:00:05)
      - BBB_BEGIN_INTRO_AT=
      # end intro after (optional, e.g. 01:00:00 - after one hour)
      - BBB_END_INTRO_AT=
      # Media server url:
      - BBB_STREAM_URL=rtmp://a.rtmp.youtube.com/live2/stream/stream_key
      # Resolution to be streamed/downloaded in format WxH (default 1920x1080)
      - BBB_RESOLUTION=1920x1080
      # stream video bitrate
      - FFMPEG_STREAM_VIDEO_BITRATE=4000
      # threads used for stream (0=auto)
      - FFMPEG_STREAM_THREADS=0
      # Timezone (default: Europe/Vienna):
      - TZ=Europe/Vienna

    volumes:
      - ./videodata:/video
```

When I user `docker-compose up` live user joins and then it leaves-

`Recreating liveStreaming ... done
Attaching to liveStreaming
liveStreaming   | Setting up nsswrapper mapping 1001 to lithium
liveStreaming   | Starting pulseaudio...
liveStreaming   | Waiting for pulseaudio to start...
liveStreaming   | Skipping nsswrapper setup - already initialized
liveStreaming   | INFO:root:Starting browser!!
liveStreaming   | INFO:root:Open BBB and hide elements!!
liveStreaming   | INFO:root:get_join_url...
liveStreaming   | INFO:root:https://some_url/bigbluebutton/api/join?meetingID=d34eec2b-904e-441d-8ff5-3c73af4b0d8a&fullName=Live&password=ut2%23%281%218&userdata-bbb_auto_join_audio=true&userdata-bbb_enable_video=true&userdata-bbb_listen_only_mode=true&userdata-bbb_force_listen_only=true&userdata-bbb_skip_check_audio=true&joinViaHtml5=true&checksum=5a0b8b6313fcff339643b436117ffc910ba895ed
liveStreaming   | INFO:root:Waiting for chat input window to appear.
liveStreaming   | Traceback (most recent call last):
liveStreaming   |   File "stream.py", line 262, in <module>
liveStreaming   |     bbb_browser()
liveStreaming   |   File "stream.py", line 144, in bbb_browser
liveStreaming   |     WebDriverWait(browser, selenium_timeout).until(element)
liveStreaming   |   File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/support/wait.py", line 80, in until
liveStreaming   |     raise TimeoutException(message, screen, stacktrace)
liveStreaming   | selenium.common.exceptions.TimeoutException: Message: 
liveStreaming   | 
liveStreaming exited with code 1
`
Thank you
