### ISSUE TITLE
Can not send chat from BB live meeting to youtube

### ISSUE THREAD

**Issue by DidierDrogbaa** [aau-zid/BigBlueButton-liveStreaming#147]
Hello, First of all I would like to say thanks to the contributors of this repo.

I was successfully able to run both `chat.py` and `stream.py` without an issue but the only problem I am facing is when live streaming I was not able to post comments from youtube to BigBlueButton live or vice versa. can anyone please explain why it's happening.
below is `docker-compose.yml` file for `chat.py`-
```
version: "3.3"
services:
  redis:
    image: redis
    networks:
     - app-tier
  bbb-streamer:
    image: 36306708c5b2
    shm_size: '2gb'
    environment:
        # BigBlueButton Server url:
      - BBB_URL=https://some_domain/bigbluebutton/api/
      # BigBlueButton secret:
      - BBB_SECRET=vOIxIbVyXS6xI4qiX94QO1kxoT42ITp58bJb3W1yDKI
      # BigBlueButton meetingID:
      - BBB_MEETING_ID=2ece330d-f2ee-4253-9650-b81ee6fb41cd
      # Media server url:
      - BBB_STREAM_URL=["rtmp://a.rtmp.youtube.com/live2/u8am-vr6f-9dj7-5gh7-6xrm"]
      # Enable chat functionality
      - BBB_ENABLE_CHAT=true
      # show chat in live stream
      - BBB_SHOW_CHAT=false
      # Message to post in BBB Chat when joining a conference
      - BBB_CHAT_MESSAGE=Viewers of the live stream can now send messages to this meeting
      # Set REDIS host (default: 'redis')
      - BBB_REDIS_HOST=redis
      # Set REDIS channel to subscribe (default: 'chat')
      - BBB_REDIS_CHANNEL=chat
      # Username for the chat (default: 'Chat')
      - BBB_CHAT_NAME=Chat
    networks:
      - app-tier
networks:
  app-tier:
    driver: bridge
```
getting this error when running php files-
`127.0.0.1:49496 [500]: POST /sendChatMessage.php - syntax error, unexpected end of file in /home/dir/Desktop/BigBlueButton-liveStreaming-master/examples/sendChatMessage.php on line 8`
Thanks :)
