### ISSUE TITLE
Failed to start livestream

### ISSUE THREAD

**Issue by julienrat** [aau-zid/BigBlueButton-liveStreaming#34]
Trying to start livestream .... but doesn't work for me ... ideas ?
`
liveStreaming   |   libpostproc    55.  5.100 / 55.  5.100
liveStreaming   | false: No such file or directory
liveStreaming   | INFO:root:Open BBB and hide elements!!
liveStreaming   | INFO:root:create_meeting...
liveStreaming   | INFO:root:A meeting already exists with that meeting ID. Please use a different meeting ID.
liveStreaming   | INFO:root:get_join_url...
liveStreaming   | Traceback (most recent call last):
liveStreaming   |   File "stream.py", line 157, in <module>
liveStreaming   |     bbb_browser()
liveStreaming   |   File "stream.py", line 75, in bbb_browser
liveStreaming   |     WebDriverWait(browser, selelnium_timeout).until(element)
liveStreaming   |   File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/support/wait.py", line 80, in until
liveStreaming   |     raise TimeoutException(message, screen, stacktrace)
liveStreaming   | selenium.common.exceptions.TimeoutException: Message: 
liveStreaming   | 
liveStreaming exited with code 1
root@ns3127147:~# 
`

**Comment by mtsonline** [comment]
"liveStreaming | false: No such file or directory liveStreaming |"
what exactly are you doing and what does your config look like?

**Comment by mtsonline** [comment]
"liveStreaming | false: No such file or directory liveStreaming |"

What exactly are you doing?
and what does your config look like?

**Comment by julienrat** [comment]
Like this :
version: '3.3'
services:
  bbb-streamer:
    image: aauzid/bigbluebutton-livestreaming
    container_name: liveStreaming
    environment:
      # BigBlueButton Server url:
      - BBB_URL=https://bbbdbloc.ovh/bigbluebutton/api
      # BigBlueButton secret:
      - BBB_SECRET=2SyuA0KGcmQtTXXXXXXXXXXXXXXXXXXXXXYlzsbNw
      # BigBlueButton meetingID:
      - BBB_MEETING_ID=09XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      # start meeting (optional):
      - BBB_START_MEETING=false
      # attendee password (optional - has to be set to the attendee password of moodle/greenlight or any other frontend to allow joining via their links):
      - BBB_ATTENDEE_PASSWORD=XXXXXXXXXXXXXX
      # moderator password (optional - has to be set to the moderator password of moodle/greenlight or any other frontend to allow joining via their links):
      - BBB_MODERATOR_PASSWORD=XXXXXXXXXXXXXXXX
      # meeting title (optional):
      - BBB_MEETING_TITLE=liveStreaming Test
      # download / save BigBlueButton meeting
      - BBB_DOWNLOAD_MEETING=false
      # play intro file (can be a local file in videodata folder e.g. /video/intro.mp4 or a url of a mediastream e.g. https://my.intro.stream)
      - BBB_INTRO=false
      # begin the intro at position (optional, e.g. 00:00:05)
      - BBB_BEGIN_INTRO_AT=04:40
      # end intro after (optional, e.g. 01:00:00 - after one hour)
      - BBB_END_INTRO_AT=
      # Media server url:
      - BBB_STREAM_URL=rtmp://a.rtmp.youtube.com/live2/XXXXXXXXXXXXXXXXXX
      # Timezone (default: Europe/Vienna):
      - TZ=Europe/Vienna

  volumes:
      - ./videodata:/video

**Comment by julienrat** [comment]
I'm trying to stream on youtube

**Comment by erenilhan** [comment]
Hi @mtsonline 
I have a same problem. I use Turkish and your stream.py file in docker (aria-label). But I get an error.
The user named "Live" join in but about 1 mins after it leave. 
Errors log output is here;
```
INFO:root:get_join_url...
Traceback (most recent call last):
File "stream.py", line 157, in <module>
bbb_browser()
File "stream.py", line 75, in bbb_browser
WebDriverWait(browser, selelnium_timeout).until(element)
File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/support/wait.py", line 80, in until
raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:
```

**Comment by erenilhan** [comment]
Hi @mtsonline 
I have a same problem. I use Turkish and changed stream.py file in docker (aria-label). But I get an error.
The user named "Live" join in but about 1 mins later it leave. 
Errors log output is here;
```
INFO:root:get_join_url...
Traceback (most recent call last):
File "stream.py", line 157, in <module>
bbb_browser()
File "stream.py", line 75, in bbb_browser
WebDriverWait(browser, selelnium_timeout).until(element)
File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/support/wait.py", line 80, in until
raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:
```

**Comment by mtsonline** [comment]
@erenilhan your bbb has to provide english language because selenium relys on the english labels. If you do not remove english and the browser decides which language to use it should work, even if you have turkish as second language available.
 

@julienrat 
please give the exact commands you try to use. thanks

**Comment by erenilhan** [comment]
@mtsonline thank you very much. I will try.

**Comment by julienrat** [comment]
@mtsonline I have followed your instructions in README file, and i launch with docker compose up

**Comment by mtsonline** [comment]
@julienrat ...I guess yur streamer searches for the intro file named "false"
>- BBB_INTRO=false

try to remove the "false" I guess then it should work.
cheers
Martin

**Comment by erenilhan** [comment]
yes @mtsonline its working now! 👍  thanks.
also @julienrat  BBB_STREAM_URL
   - BBB_STREAM_URL=rtmp://a.rtmp.youtube.com/live2/**stream**/XXXXXXXXXXX
if you add /stream/ parameters its will work on youtube.

**Comment by julienrat** [comment]
![image](https://user-images.githubusercontent.com/5439197/83447480-cfde1b00-a450-11ea-9214-76116eda20e4.png)

**Comment by julienrat** [comment]
now ! 
No false error ;)

**Comment by julienrat** [comment]
I have the impression that the selenium browser is waiting for click ...
and the timeout takes over

**Comment by ontimond** [comment]
> @erenilhan your bbb has to provide english language because selenium relys on the english labels. If you do not remove english and the browser decides which language to use it should work, even if you have turkish as second language available.
> 
> @julienrat
> please give the exact commands you try to use. thanks

Where can I adjust the settings for the language?

**Comment by mtsonline** [comment]
the liveStreaming docker container uses english language - you cannot change this and the browser even will show the english labels.

why would you need to change it? It won't hurt to not remove english language from bbb - you do not have to use it if you do not need it though.

**Comment by ontimond** [comment]
Ok now I understand it, I assumed that it must be configured somewhere, even so I still have the same problem, the echo test is activated also
```
$ docker-compose up
Recreating liveStreaming ... done
Attaching to liveStreaming
liveStreaming   | INFO:root:Starting browser!!
liveStreaming   | INFO:root:Open BBB and hide elements!!
liveStreaming   | INFO:root:create_meeting...
liveStreaming   | INFO:root:get_join_url...
liveStreaming   | Traceback (most recent call last):
liveStreaming   |   File "stream.py", line 157, in <module>
liveStreaming   |     bbb_browser()
liveStreaming   |   File "stream.py", line 75, in bbb_browser
liveStreaming   |     WebDriverWait(browser, selelnium_timeout).until(element)
liveStreaming   |   File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/support/wait.py", line 80, in until
liveStreaming   |     raise TimeoutException(message, screen, stacktrace)
liveStreaming   | selenium.common.exceptions.TimeoutException: Message: 
liveStreaming   | 
liveStreaming exited with code 1
```

and this is my docker-compose 
```
version: '3.3'
services:
  bbb-streamer:
    image: aauzid/bigbluebutton-livestreaming
    container_name: liveStreaming
    environment:
      # BigBlueButton Server url:
      - BBB_URL=https://live.xxxx.com/bigbluebutton/api
      # BigBlueButton secret:
      - BBB_SECRET=xxxxxx
      # BigBlueButton meetingID:
      - BBB_MEETING_ID=1#test+streaming+3
      # start meeting (optional):
      - BBB_START_MEETING=false
      # attendee password (optional - has to be set to the attendee password of moodle/greenlight or any other frontend to allow joining via their links):
      - BBB_ATTENDEE_PASSWORD=kDQE8
      # moderator password (optional - has to be set to the moderator password of moodle/greenlight or any other frontend to allow joining via their links):
      - BBB_MODERATOR_PASSWORD=DpSpZQuT
      # meeting title (optional):
      - BBB_MEETING_TITLE=liveStreaming Test
      # download / save BigBlueButton meeting
      - BBB_DOWNLOAD_MEETING=false
      # play intro file (can be a local file in videodata folder e.g. /video/intro.mp4 or a url of a mediastream e.g. https://my.intro.stream)
      # - BBB_INTRO=false
      # begin the intro at position (optional, e.g. 00:00:05)
      # - BBB_BEGIN_INTRO_AT=04:40
      # end intro after (optional, e.g. 01:00:00 - after one hour)
      # - BBB_END_INTRO_AT=
      # Media server url:
      - BBB_STREAM_URL=rtmp://a.rtmp.youtube.com/live2/stream/xxxxxx
      # Timezone (default: Europe/Vienna):
      - TZ=Europe/Vienna

    volumes:
      - ./videodata:/video
```

**Comment by mtsonline** [comment]
which version of bbb are you using?
are you sure you did not do any changes? This still shows, that selenium cannot find the label it expects.

**Comment by ontimond** [comment]
```
$ bbb-conf --version

ii  bbb-apps                              1:2.2.0-45                                      amd64        BigBlueButton applications for Red5
ii  bbb-apps-akka                         2.2.0-87                                        all          BigBlueButton Apps (Akka)
ii  bbb-apps-screenshare                  1:2.2.0-45                                      amd64        BigBlueButton screenshare module for Red5
ii  bbb-apps-sip                          1:2.2.0-11                                      amd64        BigBlueButton SIP module for Red5
ii  bbb-apps-video                        1:2.2.0-42                                      amd64        BigBlueButton video module for Red5
ii  bbb-apps-video-broadcast              1:2.2.0-8                                       amd64        BigBlueButton video broadcast module for Red5
ii  bbb-client                            1:2.2.0-40                                      amd64        BigBlueButton Flash client
ii  bbb-config                            1:2.2.0-191                                     amd64        BigBlueButton configuration utilities
ii  bbb-demo                              1:2.2.0-9                                       amd64        BigBlueButton API demos
ii  bbb-etherpad                          1:2.2.0-51                                      amd64        The EtherPad Lite components for BigBlueButton
ii  bbb-freeswitch-core                   2:2.2.0-112                                     amd64        BigBlueButton build of FreeSWITCH
ii  bbb-freeswitch-sounds                 1:1.6.7-6                                       amd64        FreeSWITCH Sounds
ii  bbb-fsesl-akka                        2.2.0-65                                        all          BigBlueButton FS-ESL (Akka)
ii  bbb-html5                             1:2.2.0-937                                     amd64        The HTML5 components for BigBlueButton
ii  bbb-mkclean                           1:0.8.7-3                                       amd64        Clean and optimize Matroska and WebM files
ii  bbb-playback-presentation             1:2.2.0-30                                      amd64        BigBluebutton playback of presentation
ii  bbb-record-core                       1:2.2.0-66                                      amd64        BigBlueButton record and playback
ii  bbb-red5                              1:1.0.10-16                                     amd64        The Red5 server for BigBlueButton
ii  bbb-transcode-akka                    2.2.0-8                                         all          BigBlueButton Transcoder
ii  bbb-web                               1:2.2.0-130                                     amd64        BigBlueButton API
ii  bbb-webrtc-sfu                        1:2.2.0-99                                      amd64        BigBlueButton WebRTC SFU
ii  bigbluebutton                         1:2.2.0-5                                       amd64        Open source web conferencing platform (bbb)
ii  ffmpeg                                7:4.2.2-1bbb1~ubuntu16.04                       amd64        Tools for transcoding, streaming and playing of multimedia files
ii  libavcodec58:amd64                    7:4.2.2-1bbb1~ubuntu16.04                       amd64        FFmpeg library with de/encoders for audio/video codecs - runtime files
ii  libavdevice58:amd64                   7:4.2.2-1bbb1~ubuntu16.04                       amd64        FFmpeg library for handling input and output devices - runtime files
ii  libavfilter7:amd64                    7:4.2.2-1bbb1~ubuntu16.04                       amd64        FFmpeg library containing media filters - runtime files
ii  libavformat58:amd64                   7:4.2.2-1bbb1~ubuntu16.04                       amd64        FFmpeg library with (de)muxers for multimedia containers - runtime files
ii  libavresample4:amd64                  7:4.2.2-1bbb1~ubuntu16.04                       amd64        FFmpeg compatibility library for resampling - runtime files
ii  libavutil56:amd64                     7:4.2.2-1bbb1~ubuntu16.04                       amd64        FFmpeg library with functions for simplifying programming - runtime files
ii  libopusenc0                           0.2.1-1bbb1                                     amd64        High-level API for encoding Ogg Opus audio streams
ii  libpostproc55:amd64                   7:4.2.2-1bbb1~ubuntu16.04                       amd64        FFmpeg library for post processing - runtime files
ii  libswresample3:amd64                  7:4.2.2-1bbb1~ubuntu16.04                       amd64        FFmpeg library for audio resampling, rematrixing etc. - runtime files
ii  libswscale5:amd64                     7:4.2.2-1bbb1~ubuntu16.04                       amd64        FFmpeg library for image scaling and various conversions - runtime files

```

**Comment by mtsonline** [comment]
please do bbb-conf --check and have a look at the top, there is the correct bbb version - and please only post the version not the whole output

**Comment by ontimond** [comment]
Ok sorry, the version is `2.2.17`

**Comment by mtsonline** [comment]
hm... this should work - did not hear about any problems with the recent versions.
so it really looks as if there is a setting other than the default, that interfears. 
how do you create the meeting? via greenlight?
did you try to configure LiveStreaming to join as moderator and let it start the meeting itself?

**Comment by ontimond** [comment]
When I create and start the conference by greenlight, I copy the meeting id in the docker-compose and live works without problems, but when I try to create a conference from the docker-compose itself, assigning a random meeting id, that's when it generates the error

**Comment by mtsonline** [comment]
would have been helpful if you had described this earlier.

so the problem is not, that streaming does not work, but that you where not able to configure the liveStreaming to create and start a meeting.
how does your docker-compose configuration look like? 
how did you generate the id or didn't you specify one?
Did you set passwords?...

**Comment by ontimond** [comment]
```
version: '3.3'
services:
  bbb-streamer:
    image: aauzid/bigbluebutton-livestreaming
    container_name: liveStreaming
    environment:
      # BigBlueButton Server url:
      - BBB_URL=https://live.xxxx.com/bigbluebutton/api
      # BigBlueButton secret:
      - BBB_SECRET=xxxxxx
      # BigBlueButton meetingID:
      - BBB_MEETING_ID=1#test+streaming+3
      # start meeting (optional):
      - BBB_START_MEETING=false
      # attendee password (optional - has to be set to the attendee password of moodle/greenlight or any other frontend to allow joining via their links):
      - BBB_ATTENDEE_PASSWORD=kDQE8
      # moderator password (optional - has to be set to the moderator password of moodle/greenlight or any other frontend to allow joining via their links):
      - BBB_MODERATOR_PASSWORD=DpSpZQuT
      # meeting title (optional):
      - BBB_MEETING_TITLE=liveStreaming Test
      # download / save BigBlueButton meeting
      - BBB_DOWNLOAD_MEETING=false
      # play intro file (can be a local file in videodata folder e.g. /video/intro.mp4 or a url of a mediastream e.g. https://my.intro.stream)
      # - BBB_INTRO=false
      # begin the intro at position (optional, e.g. 00:00:05)
      # - BBB_BEGIN_INTRO_AT=04:40
      # end intro after (optional, e.g. 01:00:00 - after one hour)
      # - BBB_END_INTRO_AT=
      # Media server url:
      - BBB_STREAM_URL=rtmp://a.rtmp.youtube.com/live2/stream/xxxxxx
      # Timezone (default: Europe/Vienna):
      - TZ=Europe/Vienna

    volumes:
      - ./videodata:/video
```

It is this same configuration, before executing the docker-compose there was no meeting with that id, so in this case I put `1#test+streaming+3`, I ran it and got the error, then I checked if it was created the meeting and yes it was created, I confirmed it with the meeting list using the api.
