### ISSUE TITLE
File "stream.py", line 82, in bbb_browser

### ISSUE THREAD

**Issue by bhuvankrishna** [aau-zid/BigBlueButton-liveStreaming#69]
**When starting the docker I am getting an error at line 82 related to Send Message**
browser.find_elements_by_css_selector('[aria-label="Send message"]')[0].click()

**To Reproduce**
1. Clone the latest master
2. Copy examples/docker-compose.yml.example to docker-compose.yml
3. Edit the file and add the required paramenters. My file has these parameters and commented out others

```
version: '3.3'
services:
  bbb-streamer:
    image: aauzid/bigbluebutton-livestreaming
    container_name: liveStreaming
    environment:
      # BigBlueButton Server url:
      - BBB_URL=https://<instance url>/bigbluebutton/api
      # BigBlueButton secret:
      - BBB_SECRET=<secret>
      # BigBlueButton meetingID:
      - BBB_MEETING_ID=<Meeting ID>
      - BBB_STREAM_URL=rtmp://<streamurl>/app/
      # Timezone (default: Europe/Vienna):
      - TZ=<timezone>
#    volumes:
#      - ./videodata:/video
```
4. I started `docker-compose up`. I did not use -d to see if any errors are shown.
5. And this erorr is shown

**Output of the error**
```
Traceback (most recent call last):
liveStreaming   |   File "stream.py", line 164, in <module>
liveStreaming   |     bbb_browser()
liveStreaming   |   File "stream.py", line 82, in bbb_browser
liveStreaming   |     browser.find_elements_by_css_selector('[aria-label="Send message"]')[0].click()
liveStreaming   |   File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webelement.py", line 80, in click
liveStreaming   |     self._execute(Command.CLICK_ELEMENT)
liveStreaming   |   File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
liveStreaming   |     return self._parent.execute(command, params)
liveStreaming   |   File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
liveStreaming   |     self.error_handler.check_response(response)
liveStreaming   |   File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
liveStreaming   |     raise exception_class(message, screen, stacktrace)
liveStreaming   | selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <button aria-label="Send message" aria-disabled="false" class="md--Q7ug4 buttonWrapper--x8uow sendButton--Z93EzE" type="submit" position="bottom" id="tippy-46">...</button> is not clickable at point (500, 1025). Other element would receive the click: <div class="ReactModal__Overlay ReactModal__Overlay--after-open overlay--Z7FUVK">...</div>
liveStreaming   |   (Session info: chrome=84.0.4147.125)
liveStreaming   | 
liveStreaming exited with code 1
```

**Desktop (please complete the following information):**
 - OS: Debian Unstable, Ubuntu 18.04

I tried to comment the line 82 `browser.find_elements_by_css_selector('[aria-label="Send message"]')[0].click()` and build a new image and try to run I get another error on line 87 which is `browser.find_elements_by_id('chat-toggle-button')[0].click()`

I think line 87 has to do with hiding chat window. I am not sure how to trace what went wrong.
